/**
 * Created by John on 23/02/2015.
 */
public enum State {
    OFF, MAIN_MENU, CONTACTS_MENU, ADD_CONTACT, REMOVE_CONTACT,
    TEXTS_MENU, WHO_TO_TEXT, ENTER_TEXT, RECEIVE_TEXT,
    CALLS_MENU, WHO_TO_CALL, RECORD_CALL, RECEIVE_CALL,
    SET_PASSCODE, ENTER_PASSCODE;
}
